CREATE DATABASE HRMS
GO
use HRMS
CREATE TABLE tb_Login (
	ID INT IDENTITY NOT NULL,
	Name VARCHAR ( 50 ),
	Password VARCHAR ( 50 ),
	CONSTRAINT PK_tb_Login PRIMARY KEY CLUSTERED (ID)
	)
GO
CREATE TABLE tb_StuffBasic (
	ID INT IDENTITY NOT NULL,
	Name NVARCHAR ( 25 ),
	Sex NVARCHAR ( 25 ),
	Position NVARCHAR ( 25 ),
	Phone NVARCHAR ( 25 ),
	Address NVARCHAR ( 64 ),
	Email NVARCHAR ( 25 ),
	Photo IMAGE,
	CONSTRAINT PK_tb_StuffBasic PRIMARY KEY CLUSTERED (ID)
	)
GO

